---
   
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install virtual-box"
  become: true
  apt:
    name: virtualbox
    state: latest
    update_cache: yes
    
- name: "install brew"
  become: true
  apt:
    name: linuxbrew-wrapper
    state: latest
    update_cache: yes
    
- name: "install minikube"
  become: true
  brew:
    name: minikube
    state: latest
    update_cache: yes