---
   
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"


# Install virtual box
- import_tasks: install-virtual-box-full.yml

# Install minikube
- import_tasks: install-minikube.yml