---
   
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install virtual-box"
  become: true
  apt:
    name: virtualbox
    state: latest
    update_cache: yes
    
- name: "install virtual-box"
  become: true
  apt:
    name: git
    state: latest
    update_cache: yes
    
- name: "install brew"
  become: true
  shell: |
    git clone https://github.com/Homebrew/linuxbrew.git ~/.linuxbrew
    export PATH="$HOME/.linuxbrew/bin:$PATH"
    export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
    export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
    
- name: "install minikube"
  become: true
  shell: brew install minikube