---
   
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"
    
- name: "install curl"
  become: true
  apt:
    name: curl
    state: latest
    update_cache: yes
    
- name: "install apt-transport-https"
  become: true
  apt:
    name: apt-transport-https
    state: latest
    update_cache: yes

- name: "install virtual-box"
  become: true
  apt:
    name: virtualbox
    state: latest
    update_cache: yes

- name: Download minikube installer
  become: true
  get_url: 
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /tmp/
    mode: '0777'

- name: Copy /tmp/minikube-linux-amd64 to /usr/local/bin/minikube
  become: true
  copy:
    src: "/tmp/minikube-linux-amd64"
    dest: "/usr/local/bin/minikube"
    remote_src: yes
    mode: '0777'

- name: "get minikube version"
  become: true
  shell: minikube version
  
- name: Remove /tmp/minikube-linux-amd64
  become: true
  file: 
    path: /tmp/minikube-linux-amd64
    state: absent
    
- name: get kubectl url
  become: true
  shell: echo https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
  register: kubectl_url  
- debug: var=kubectl_url.stdout_lines
    
- name: Download kubectl
  become: true
  get_url: 
    url: "{{ kubectl_url.stdout }}"
    dest: /tmp/
    mode: '0777'   
  register: download_kubectl  
- debug: var=download_kubectl.stdout_lines

- name: Copy /tmp/kubectl to /usr/local/bin/kubectl
  become: true
  copy:
    src: "/tmp/kubectl"
    dest: "/usr/local/bin/kubectl"
    remote_src: yes
    mode: '0777'
    
- name: "get kubectl help"
  become: true
  shell: kubectl --help
  register: kubectl_help  
- debug: var=kubectl_help.stdout_lines

- name: Remove /tmp/kubectl
  become: true
  file: 
    path: /tmp/kubectl
    state: absent