---

- name: minikube start
  become: yes
  shell: |
    minikube start --driver=none
    kubectl config view
  register: minikube_start
- debug: var=minikube_start.stdout_lines
    
- name: minikube get nodes
  become: yes
  shell: |
    kubectl get nodes
  register: get_nodes
- debug: var=get_nodes.stdout_lines
    
- name: minikube deploy
  become: true
  shell: |
    kubectl create deploy aws-devops-capstone --image=minh1302/aws-devops-capstone
  register: minikube_deploy
- debug: var=minikube_deploy.stdout_lines
    
- name: Wait for pods to be ready
  become: true
  shell: "kubectl get pods"
  register: pods
  until:      
    - '" Running "  in pods.stdout'      
  retries: 50
  delay: 5
- debug: var=pods.stdout_lines
    
- name: minikube port forward
  become: true
  shell: kubectl port-forward deployment/aws-devops-capstone --address 0.0.0.0 3030:3030
  register: minikube_port_forward
- debug: var=minikube_port_forward.stdout_lines