---

- name: minikube start
  become: yes
  shell: |
    minikube start --driver=none
    kubectl config view
  register: minikube_start
- debug: var=minikube_start.stdout_lines
    
- name: minikube deploy
  become: yes
  shell: |
    dockerpath=minh1302/aws-devops-capstone
    kubectl get nodes
    kubectl create deploy aws-devops-capstone --image=minh1302/aws-devops-capstone
    kubectl get deploy,rs,svc,pods
  register: minikube_deploy
- debug: var=minikube_deploy.stdout_lines
    
- name: Wait for nodes to be ready
  shell: "kubectl get nodes"
  register: nodes
  until:      
    - '" Ready "  in nodes.stdout'      
  retries: 50
  delay: 5
- debug: var=nodes.stdout_lines
    
- name: minikube port forward
  become: yes
  shell: kubectl port-forward deployment/aws-devops-capstone --address 0.0.0.0 3030:3030
  register: minikube_port_forward
- debug: var=minikube_port_forward.stdout_lines