---

- name: minikube start
  become: yes
  shell: |
    minikube start
    kubectl config view
    
- name: minikube deploy
  become: yes
  shell: |
    dockerpath=minh1302/aws-devops-capstone
    kubectl get nodes
    kubectl create deploy aws-devops-capstone --image=minh1302/aws-devops-capstone
    kubectl get deploy,rs,svc,pods
    
- name: wait for pods to come up
  become: yes
  shell: kubectl get pods -o json
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
    
- name: minikube port forward
  become: yes
  shell: |
    kubectl port-forward deployment/aws-devops-capstone --address 0.0.0.0 3030:3030