
    
#   - name: Check for Starship command
#   command: command -v starship >/dev/null 2>&1
#   register: installed
#   no_log: true
#   ignore_errors: yes

# - name: Download Starship installer
#   get_url:
#     url: https://starship.rs/install.sh
#     dest: /tmp/starship-installer.sh
#     mode: 'u+rwx'
#   when: installed.rc != 0
#   register: download

# - name: Run the install script
#   shell: /tmp/starship-installer.sh
#   when: download.changed

# - name: Remove the starship-installer.sh
#   file:
#     path: /tmp/starship-installer.sh
#     state: absent

    #  - name: checking raid status 
    #   shell: "cat /proc/mdstat | grep 'F' | cut -d' ' -f6 | cut -d'[' -f1" 
    #   register: "array_check"

    #  - debug:
    #     msg: "{{ array_check.stdout_lines }}"

    #  - name: checking the samrtctl logs for the drive 
    #   shell: "/usr/sbin/smartctl -H /dev/{{ item }} | tail -2|awk -F' ' '{print $6}'"
    #   with_items:
    #      - "nvme0"
    #      - "nvme1"
    #   register: "smartctl_status"